
all:
    gcc -o client client.c-lsocket -lnsl -lresolv
    gcc -o serverM serverM.c-lsocket -lnsl -lresolv
    gcc -o serverCS serverCS.c -lsocket -lnsl -lresolv
    gcc -o serverEE serverEE.c -lsocket -lnsl -lresolv
    gcc -o serverC serverC.c-lsocket -lnsl -lresolv
    
    $(phony serverEE):
        ./serverEE
        
    serverCS:
        ./serverCS
                    
    serverC:
        ./serverC
        
    serverM:
        ./serverM
